# Generated by Django 2.2 on 2019-05-03 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('student', models.BooleanField(default=False, help_text='For Students Permissions')),
                ('teacher', models.BooleanField(default=False, help_text='For Teachers Permissions')),
                ('principal', models.BooleanField(default=False, help_text='For Principal permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('landmark', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '88855599test@gmail.com97'. Up to 12 digits allowed along with country code.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, null=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=True, max_length=50)),
                ('Message', models.TextField(default=True)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('video1', models.URLField(blank=True, null=True)),
                ('video2', models.URLField(blank=True, null=True)),
                ('school_brouche', models.FileField(blank=True, null=True, upload_to='')),
                ('SchoolProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MediaUpload', to='account.SchoolProfile')),
            ],
        ),
    ]
