# Generated by Django 2.2 on 2019-04-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='Title',
            new_name='title',
        ),
    ]
