# Generated by Django 2.2 on 2019-05-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('whole_year_calender', models.FileField(blank=True, null=True, upload_to='')),
                ('sepcial_holidays', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
