# Generated by Django 2.2 on 2019-05-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolclasses', '0001_initial'),
        ('account', '0002_academiccalender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_timetable', models.ImageField(blank=True, null=True, upload_to='')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TimeTable', to='schoolclasses.Class')),
                ('student_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TimeTable', to='schoolclasses.Section')),
            ],
        ),
    ]
