# Generated by Django 2.2 on 2019-04-22 08:03

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190422_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='none', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '8885559997'. Up to 12 digits allowed along with country code.", regex='^\\+?1?\\d{9,15}$')])),
                ('subject_expertise', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('english', 'ENGLISH'), ('hindi', 'HINDI'), ('maths', 'MATHS'), ('science', 'SCIENCE'), ('social science', 'SOCIAL_SCIENCE')], max_length=42, null=True)),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('classes_alloted', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('nur', 'NUR'), ('lkg', 'LKG'), ('ukg', 'UKG'), ('1st', '1ST'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=62, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
