# Generated by Django 2.2 on 2019-04-22 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='Message',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='Title',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
