# Generated by Django 2.2 on 2019-05-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='upload_syllabus',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
