# Generated by Django 2.2 on 2019-04-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190422_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
