# Generated by Django 2.2 on 2019-05-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190507_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalender',
            name='sepcial_holidays',
            field=models.FileField(blank=True, null=True, upload_to='calender/'),
        ),
        migrations.AlterField(
            model_name='academiccalender',
            name='whole_year_calender',
            field=models.FileField(blank=True, null=True, upload_to='calender/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alert_image/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='upload_syllabus',
            field=models.ImageField(blank=True, null=True, upload_to='syllabus/'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='upload_timetable',
            field=models.ImageField(blank=True, null=True, upload_to='timetable/'),
        ),
    ]
