# Generated by Django 2.2 on 2019-05-11 11:51

import ckeditor_uploader.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolclasses', '__first__'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, max_length=8, null=True)),
                ('mobile_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '8885559997'. Up to 12 digits allowed along with country code.", regex='^\\+?1?\\d{9,15}$')])),
                ('subject_expertise', multiselectfield.db.fields.MultiSelectField(choices=[('english', 'ENGLISH'), ('hindi', 'HINDI'), ('maths', 'MATHS'), ('science', 'SCIENCE'), ('social science', 'SOCIAL_SCIENCE')], max_length=42)),
                ('experience', models.PositiveSmallIntegerField()),
                ('joining_date', models.DateField(blank=True, max_length=8, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('highest_qualification', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.SchoolProfile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_title', models.CharField(max_length=255)),
                ('upload_homework', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.SchoolProfile')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='schoolclasses.Class')),
                ('student_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='schoolclasses.Section')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='employes.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo_1', models.ImageField(blank=True, upload_to='')),
                ('photo_2', models.ImageField(blank=True, upload_to='')),
                ('photo_3', models.ImageField(blank=True, upload_to='')),
                ('photo_4', models.ImageField(blank=True, upload_to='')),
                ('photo_5', models.ImageField(blank=True, upload_to='')),
                ('photo_6', models.ImageField(blank=True, upload_to='')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.SchoolProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=255)),
                ('upload_assignment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.SchoolProfile')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='schoolclasses.Class')),
                ('student_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='schoolclasses.Section')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='employes.Teacher')),
            ],
        ),
    ]
