# Generated by Django 2.2 on 2019-04-24 12:17

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=True, max_length=20)),
                ('username', models.CharField(default=True, max_length=15, unique=True)),
                ('age', models.PositiveSmallIntegerField(default=1)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default=True, max_length=10)),
                ('date_of_birth', models.DateField(default=True, max_length=8)),
                ('mobile_number', models.CharField(default=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '8885559997'. Up to 12 digits allowed along with country code.", regex='^\\+?1?\\d{9,15}$')])),
                ('subject_expertise', multiselectfield.db.fields.MultiSelectField(choices=[('english', 'ENGLISH'), ('hindi', 'HINDI'), ('maths', 'MATHS'), ('science', 'SCIENCE'), ('social science', 'SOCIAL_SCIENCE')], default=True, max_length=42)),
                ('experience', models.PositiveSmallIntegerField(default=True)),
                ('joining_date', models.DateField(default=True, max_length=8)),
                ('email_id', models.EmailField(default=True, max_length=254)),
                ('highest_qualification', models.CharField(default=True, max_length=20)),
            ],
        ),
    ]
