# Generated by Django 2.2 on 2019-05-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolclasses', '0001_initial'),
        ('employes', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='schoolclasses.Class'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='schoolclasses.Section'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='employes.Teacher'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.SchoolProfile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='schoolclasses.Class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='schoolclasses.Section'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='employes.Teacher'),
        ),
    ]
