# Generated by Django 2.2 on 2019-05-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='student_section',
        ),
    ]
