# Generated by Django 2.2 on 2019-05-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0003_remove_syllabus_student_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
