# Generated by Django 2.2 on 2019-04-18 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=20, null=True)),
                ('student_class', models.PositiveIntegerField(blank=True, null=True)),
                ('student_section', models.CharField(blank=True, max_length=5, null=True)),
                ('student_roll_number', models.CharField(blank=True, max_length=10, null=True)),
                ('student_reg_number', models.CharField(blank=True, max_length=20, null=True)),
                ('student_previous_school', models.CharField(blank=True, max_length=20, null=True)),
                ('student_previous_school_tc', models.ImageField(default=False, upload_to='')),
                ('student_batch_no', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_mobile_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '8885559997'. Up to 12 digits allowed along with country code.", regex='^\\+?1?\\d{9,15}$')])),
                ('parents_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('family_photo', models.ImageField(default=False, upload_to='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('home_address', models.CharField(blank=True, max_length=60, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
