# Generated by Django 2.2 on 2019-04-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='family_photo',
            new_name='student_previous_school_transfer_certificate',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_previous_school_tc',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='schoolclasses.Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_section',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='schoolclasses.section'),
            preserve_default=False,
        ),
    ]
