# Generated by Django 2.2 on 2019-04-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190422_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_section',
        ),
    ]
